name: Build Doxygen Document
on: [push]
      
jobs:
  build_artifacts:
    name: Build Artifacts
    runs-on: ubuntu-20.04
    steps:
      - name: Get latest code
        uses: actions/checkout@v2
      
      - name: Build doxygen document
        uses: mattnotmitt/doxygen-action@v1

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: |
            docs/*