name: Build Doxygen Document
on: [push]
jobs:
  build_artifacts:
    name: Build Artifacts
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      
      - uses: mattnotmitt/doxygen-action@v1
            
      - uses: actions/upload-artifact@v2
        with:
          name: docs
          path: |
            docs/*